"""initial schema

Revision ID: ed072039376b
Revises: 
Create Date: 2026-09-02 23:56:58.858484

"""
from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'ed072039376b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('api_key', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    schema='clever_ai'
    )
    op.create_index(op.f('ix_clever_ai_users_api_key'), 'users', ['api_key'], unique=True, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_users_created_at'), 'users', ['created_at'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_users_email'), 'users', ['email'], unique=True, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_users_role'), 'users', ['role'], unique=False, schema='clever_ai')
    op.create_table('agent_graphs',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dsl', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('canvas_layout', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('compiled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compilation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('stall_limit', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['clever_ai.users.id'], name=op.f('fk_agent_graphs_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_graphs')),
    schema='clever_ai'
    )
    op.create_index('ix_agent_graphs_owner_status', 'agent_graphs', ['owner_id', 'status'], unique=False, schema='clever_ai')
    op.create_index('ix_agent_graphs_public', 'agent_graphs', ['is_public', 'status'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_agent_graphs_created_at'), 'agent_graphs', ['created_at'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_agent_graphs_name'), 'agent_graphs', ['name'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_agent_graphs_owner_id'), 'agent_graphs', ['owner_id'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_agent_graphs_status'), 'agent_graphs', ['status'], unique=False, schema='clever_ai')
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('graph_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['clever_ai.agent_graphs.id'], name=op.f('fk_chat_sessions_graph_id_agent_graphs')),
    sa.ForeignKeyConstraint(['user_id'], ['clever_ai.users.id'], name=op.f('fk_chat_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions')),
    schema='clever_ai'
    )
    op.create_index('ix_chat_sessions_user_status', 'chat_sessions', ['user_id', 'status'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_chat_sessions_created_at'), 'chat_sessions', ['created_at'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_chat_sessions_graph_id'), 'chat_sessions', ['graph_id'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_chat_sessions_status'), 'chat_sessions', ['status'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False, schema='clever_ai')
    op.create_table('person_nodes',
    sa.Column('graph_id', sa.UUID(), nullable=False),
    sa.Column('node_key', sa.String(length=64), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('professional_role', sa.String(length=128), nullable=False),
    sa.Column('primary_duty', sa.Text(), nullable=False),
    sa.Column('persona_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('constitutional_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_provider', sa.String(length=64), nullable=True),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('top_p', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('working_memory_window', sa.Integer(), nullable=False),
    sa.Column('memory_retrieval_k', sa.Integer(), nullable=False),
    sa.Column('assigned_skill_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['clever_ai.agent_graphs.id'], name=op.f('fk_person_nodes_graph_id_agent_graphs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_nodes')),
    sa.UniqueConstraint('graph_id', 'node_key', name='uq_person_nodes_graph_key'),
    schema='clever_ai'
    )
    op.create_index(op.f('ix_clever_ai_person_nodes_created_at'), 'person_nodes', ['created_at'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_person_nodes_graph_id'), 'person_nodes', ['graph_id'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_person_nodes_node_type'), 'person_nodes', ['node_type'], unique=False, schema='clever_ai')
    op.create_index('ix_person_nodes_graph_type', 'person_nodes', ['graph_id', 'node_type'], unique=False, schema='clever_ai')
    op.create_table('graph_edges',
    sa.Column('graph_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('bidirectional', sa.Boolean(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['clever_ai.agent_graphs.id'], name=op.f('fk_graph_edges_graph_id_agent_graphs')),
    sa.ForeignKeyConstraint(['source_node_id'], ['clever_ai.person_nodes.id'], name=op.f('fk_graph_edges_source_node_id_person_nodes')),
    sa.ForeignKeyConstraint(['target_node_id'], ['clever_ai.person_nodes.id'], name=op.f('fk_graph_edges_target_node_id_person_nodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_edges')),
    schema='clever_ai'
    )
    op.create_index(op.f('ix_clever_ai_graph_edges_created_at'), 'graph_edges', ['created_at'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_graph_edges_graph_id'), 'graph_edges', ['graph_id'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_graph_edges_source_node_id'), 'graph_edges', ['source_node_id'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_graph_edges_target_node_id'), 'graph_edges', ['target_node_id'], unique=False, schema='clever_ai')
    op.create_index('ix_graph_edges_channel', 'graph_edges', ['graph_id', 'channel'], unique=False, schema='clever_ai')
    op.create_index('ix_graph_edges_source', 'graph_edges', ['source_node_id'], unique=False, schema='clever_ai')
    op.create_index('ix_graph_edges_target', 'graph_edges', ['target_node_id'], unique=False, schema='clever_ai')
    op.create_table('orchestration_runs',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_message_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('task_ledger', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('progress_ledger', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('stall_count', sa.Integer(), nullable=False),
    sa.Column('replan_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('final_response', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['clever_ai.chat_sessions.id'], name=op.f('fk_orchestration_runs_session_id_chat_sessions')),
    sa.ForeignKeyConstraint(['user_message_id'], ['clever_ai.messages.id'], name='fk_orchestration_runs_user_message', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orchestration_runs')),
    schema='clever_ai'
    )
    op.create_index(op.f('ix_clever_ai_orchestration_runs_created_at'), 'orchestration_runs', ['created_at'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_orchestration_runs_session_id'), 'orchestration_runs', ['session_id'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_orchestration_runs_status'), 'orchestration_runs', ['status'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_orchestration_runs_user_message_id'), 'orchestration_runs', ['user_message_id'], unique=False, schema='clever_ai')
    op.create_index('ix_orchestration_runs_created', 'orchestration_runs', ['created_at'], unique=False, schema='clever_ai')
    op.create_index('ix_orchestration_runs_session_status', 'orchestration_runs', ['session_id', 'status'], unique=False, schema='clever_ai')
    op.create_table('agent_memories',
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('source_run_id', sa.UUID(), nullable=True),
    sa.Column('source_session_id', sa.UUID(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['clever_ai.person_nodes.id'], name=op.f('fk_agent_memories_node_id_person_nodes')),
    sa.ForeignKeyConstraint(['source_run_id'], ['clever_ai.orchestration_runs.id'], name=op.f('fk_agent_memories_source_run_id_orchestration_runs')),
    sa.ForeignKeyConstraint(['source_session_id'], ['clever_ai.chat_sessions.id'], name=op.f('fk_agent_memories_source_session_id_chat_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_memories')),
    schema='clever_ai'
    )
    op.create_index('ix_agent_memories_embedding_hnsw', 'agent_memories', ['embedding'], unique=False, schema='clever_ai', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_agent_memories_node_type', 'agent_memories', ['node_id', 'memory_type'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_agent_memories_created_at'), 'agent_memories', ['created_at'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_agent_memories_memory_type'), 'agent_memories', ['memory_type'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_agent_memories_node_id'), 'agent_memories', ['node_id'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_agent_memories_source_run_id'), 'agent_memories', ['source_run_id'], unique=False, schema='clever_ai')
    op.create_table('agent_skills',
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('entrypoint', sa.String(length=128), nullable=False),
    sa.Column('parameters_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('origin_run_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['clever_ai.person_nodes.id'], name=op.f('fk_agent_skills_node_id_person_nodes')),
    sa.ForeignKeyConstraint(['origin_run_id'], ['clever_ai.orchestration_runs.id'], name=op.f('fk_agent_skills_origin_run_id_orchestration_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_skills')),
    sa.UniqueConstraint('node_id', 'name', 'version', name='uq_agent_skills_node_name_version'),
    schema='clever_ai'
    )
    op.create_index('ix_agent_skills_embedding_hnsw', 'agent_skills', ['embedding'], unique=False, schema='clever_ai', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_agent_skills_node_status', 'agent_skills', ['node_id', 'status'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_agent_skills_created_at'), 'agent_skills', ['created_at'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_agent_skills_name'), 'agent_skills', ['name'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_agent_skills_node_id'), 'agent_skills', ['node_id'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_agent_skills_status'), 'agent_skills', ['status'], unique=False, schema='clever_ai')
    op.create_table('messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('sender_node_id', sa.UUID(), nullable=True),
    sa.Column('recipient_node_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=True),
    sa.Column('milestone_id', sa.String(length=64), nullable=True),
    sa.Column('model_used', sa.String(length=128), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['recipient_node_id'], ['clever_ai.person_nodes.id'], name=op.f('fk_messages_recipient_node_id_person_nodes')),
    sa.ForeignKeyConstraint(['run_id'], ['clever_ai.orchestration_runs.id'], name=op.f('fk_messages_run_id_orchestration_runs')),
    sa.ForeignKeyConstraint(['sender_node_id'], ['clever_ai.person_nodes.id'], name=op.f('fk_messages_sender_node_id_person_nodes')),
    sa.ForeignKeyConstraint(['session_id'], ['clever_ai.chat_sessions.id'], name=op.f('fk_messages_session_id_chat_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    schema='clever_ai'
    )
    op.create_index(op.f('ix_clever_ai_messages_created_at'), 'messages', ['created_at'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_messages_event_type'), 'messages', ['event_type'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_messages_recipient_node_id'), 'messages', ['recipient_node_id'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_messages_role'), 'messages', ['role'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_messages_run_id'), 'messages', ['run_id'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_messages_sender_node_id'), 'messages', ['sender_node_id'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_messages_session_id'), 'messages', ['session_id'], unique=False, schema='clever_ai')
    op.create_index('ix_messages_run_created', 'messages', ['run_id', 'created_at'], unique=False, schema='clever_ai')
    op.create_index('ix_messages_sender', 'messages', ['sender_node_id', 'created_at'], unique=False, schema='clever_ai')
    op.create_index('ix_messages_session_created', 'messages', ['session_id', 'created_at'], unique=False, schema='clever_ai')
    op.create_table('post_mortem_jobs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('lessons_extracted', sa.Integer(), nullable=False),
    sa.Column('skills_compiled', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['clever_ai.orchestration_runs.id'], name=op.f('fk_post_mortem_jobs_run_id_orchestration_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_mortem_jobs')),
    schema='clever_ai'
    )
    op.create_index(op.f('ix_clever_ai_post_mortem_jobs_created_at'), 'post_mortem_jobs', ['created_at'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_post_mortem_jobs_run_id'), 'post_mortem_jobs', ['run_id'], unique=True, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_post_mortem_jobs_status'), 'post_mortem_jobs', ['status'], unique=False, schema='clever_ai')
    op.create_table('skill_executions',
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['clever_ai.person_nodes.id'], name=op.f('fk_skill_executions_node_id_person_nodes')),
    sa.ForeignKeyConstraint(['run_id'], ['clever_ai.orchestration_runs.id'], name=op.f('fk_skill_executions_run_id_orchestration_runs')),
    sa.ForeignKeyConstraint(['skill_id'], ['clever_ai.agent_skills.id'], name=op.f('fk_skill_executions_skill_id_agent_skills')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_executions')),
    schema='clever_ai'
    )
    op.create_index(op.f('ix_clever_ai_skill_executions_created_at'), 'skill_executions', ['created_at'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_skill_executions_node_id'), 'skill_executions', ['node_id'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_skill_executions_run_id'), 'skill_executions', ['run_id'], unique=False, schema='clever_ai')
    op.create_index(op.f('ix_clever_ai_skill_executions_skill_id'), 'skill_executions', ['skill_id'], unique=False, schema='clever_ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clever_ai_skill_executions_skill_id'), table_name='skill_executions', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_skill_executions_run_id'), table_name='skill_executions', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_skill_executions_node_id'), table_name='skill_executions', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_skill_executions_created_at'), table_name='skill_executions', schema='clever_ai')
    op.drop_table('skill_executions', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_post_mortem_jobs_status'), table_name='post_mortem_jobs', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_post_mortem_jobs_run_id'), table_name='post_mortem_jobs', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_post_mortem_jobs_created_at'), table_name='post_mortem_jobs', schema='clever_ai')
    op.drop_table('post_mortem_jobs', schema='clever_ai')
    op.drop_index('ix_messages_session_created', table_name='messages', schema='clever_ai')
    op.drop_index('ix_messages_sender', table_name='messages', schema='clever_ai')
    op.drop_index('ix_messages_run_created', table_name='messages', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_messages_session_id'), table_name='messages', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_messages_sender_node_id'), table_name='messages', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_messages_run_id'), table_name='messages', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_messages_role'), table_name='messages', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_messages_recipient_node_id'), table_name='messages', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_messages_event_type'), table_name='messages', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_messages_created_at'), table_name='messages', schema='clever_ai')
    op.drop_table('messages', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_agent_skills_status'), table_name='agent_skills', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_agent_skills_node_id'), table_name='agent_skills', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_agent_skills_name'), table_name='agent_skills', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_agent_skills_created_at'), table_name='agent_skills', schema='clever_ai')
    op.drop_index('ix_agent_skills_node_status', table_name='agent_skills', schema='clever_ai')
    op.drop_index('ix_agent_skills_embedding_hnsw', table_name='agent_skills', schema='clever_ai', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('agent_skills', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_agent_memories_source_run_id'), table_name='agent_memories', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_agent_memories_node_id'), table_name='agent_memories', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_agent_memories_memory_type'), table_name='agent_memories', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_agent_memories_created_at'), table_name='agent_memories', schema='clever_ai')
    op.drop_index('ix_agent_memories_node_type', table_name='agent_memories', schema='clever_ai')
    op.drop_index('ix_agent_memories_embedding_hnsw', table_name='agent_memories', schema='clever_ai', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('agent_memories', schema='clever_ai')
    op.drop_index('ix_orchestration_runs_session_status', table_name='orchestration_runs', schema='clever_ai')
    op.drop_index('ix_orchestration_runs_created', table_name='orchestration_runs', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_orchestration_runs_user_message_id'), table_name='orchestration_runs', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_orchestration_runs_status'), table_name='orchestration_runs', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_orchestration_runs_session_id'), table_name='orchestration_runs', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_orchestration_runs_created_at'), table_name='orchestration_runs', schema='clever_ai')
    op.drop_table('orchestration_runs', schema='clever_ai')
    op.drop_index('ix_graph_edges_target', table_name='graph_edges', schema='clever_ai')
    op.drop_index('ix_graph_edges_source', table_name='graph_edges', schema='clever_ai')
    op.drop_index('ix_graph_edges_channel', table_name='graph_edges', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_graph_edges_target_node_id'), table_name='graph_edges', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_graph_edges_source_node_id'), table_name='graph_edges', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_graph_edges_graph_id'), table_name='graph_edges', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_graph_edges_created_at'), table_name='graph_edges', schema='clever_ai')
    op.drop_table('graph_edges', schema='clever_ai')
    op.drop_index('ix_person_nodes_graph_type', table_name='person_nodes', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_person_nodes_node_type'), table_name='person_nodes', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_person_nodes_graph_id'), table_name='person_nodes', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_person_nodes_created_at'), table_name='person_nodes', schema='clever_ai')
    op.drop_table('person_nodes', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_chat_sessions_user_id'), table_name='chat_sessions', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_chat_sessions_status'), table_name='chat_sessions', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_chat_sessions_graph_id'), table_name='chat_sessions', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_chat_sessions_created_at'), table_name='chat_sessions', schema='clever_ai')
    op.drop_index('ix_chat_sessions_user_status', table_name='chat_sessions', schema='clever_ai')
    op.drop_table('chat_sessions', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_agent_graphs_status'), table_name='agent_graphs', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_agent_graphs_owner_id'), table_name='agent_graphs', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_agent_graphs_name'), table_name='agent_graphs', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_agent_graphs_created_at'), table_name='agent_graphs', schema='clever_ai')
    op.drop_index('ix_agent_graphs_public', table_name='agent_graphs', schema='clever_ai')
    op.drop_index('ix_agent_graphs_owner_status', table_name='agent_graphs', schema='clever_ai')
    op.drop_table('agent_graphs', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_users_role'), table_name='users', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_users_email'), table_name='users', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_users_created_at'), table_name='users', schema='clever_ai')
    op.drop_index(op.f('ix_clever_ai_users_api_key'), table_name='users', schema='clever_ai')
    op.drop_table('users', schema='clever_ai')
    # ### end Alembic commands ###
